name: tflite_testing
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:

  csv: ^5.0.2
  ffmpeg_kit_flutter_audio: ^5.1.0
  fftea: ^1.3.1
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  mp3_info: ^0.2.1
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  scidart: ^0.0.2-dev.12
  tflite_flutter: ^0.9.1
  tuple: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
